"""create operation log

Revision ID: 01efe81c6bf5
Revises:
Create Date: 2026-09-29 02:54:25.072748

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01efe81c6bf5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("ops",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ops_operation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "ops", "oldman_managed": True},
    )
    with op.batch_alter_table("ops_operation_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ops_operation_log_created_at"), ["created_at"], unique=False)

    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('ops_operation_log', 'ops', TRUE, '01efe81c6bf5')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'ops_operation_log' AND app_label = 'ops'")
    with op.batch_alter_table("ops_operation_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ops_operation_log_created_at"))

    op.drop_table("ops_operation_log")
    # ### end Alembic commands ###
